### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by AndersDJohnson** [adjohnson916/findbugs-diff#7]
Requested by @forsage.

**Comment by forsage** [comment]
Thank you so much! Also deploying to **[Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cfindbugs-diff)**?

**Comment by AndersDJohnson** [comment]
@forsage Yes, it's now on Maven Central as `me.andrz.findbugs:findbugs-diff:0.1.0` (https://repo1.maven.org/maven2/me/andrz/findbugs/findbugs-diff/0.1.0/).

**Comment by forsage** [comment]
Thanks @adjohnson916 ! Can you also put the `0.1.0-all` version to Maven Central?

**Comment by AndersDJohnson** [comment]
@forsage Sure, I've now published the `all` JAR to Maven Central ([here](https://repo1.maven.org/maven2/me/andrz/findbugs/findbugs-diff/0.1.0/findbugs-diff-0.1.0-all.jar)).

Alternatively, you could use my project [maven-bin](https://github.com/adjohnson916/maven-bin) as follows:

Install maven-bin:

```
mvn me.andrz.maven:maven-bin-maven-plugin:installSelf
```

Run `findbugs-diff`:

```
mvbn me.andrz.findbugs:findbugs-diff
```

**Comment by AndersDJohnson** [comment]
Note: eventually I'd like to make a Maven plugin too - see #4.
